INSERT INTO dbo.Jabatan (Jabatan_Id, Nama_Jabatan, Deskripsi_Jabatan)
VALUES (1, 'Ketua Umum', ' Ketua Umum adalah posisi tertinggi yang bertanggung jawab atas seluruh operasional dan kebijakan strategis organisasi tersebut.
Ketua Umum memimpin dan mengarahkan jalannya organisasi, serta memastikan tujuan organisasi tercapai dengan efektif dan efisien.'),
(2, 'Sekretaris Jendral', 'Sekretaris Jenderal (Sekjen) adalah posisi penting dalam struktur organisasi yang berperan sebagai penghubung antara pimpinan (misalnya Ketua Umum) dan anggota organisasi, serta bertanggung jawab dalam mengelola administrasi, dokumentasi, 
dan komunikasi internal maupun eksternal organisasi. Sekretaris Jenderal memiliki tanggung jawab besar dalam menjaga kelancaran operasional organisasi dan memastikan bahwa segala kegiatan serta kebijakan organisasi tercatat dan terdokumentasi dengan baik.'), 
(3, 'Sekretaris Umum', 'Sekretaris Umum (Sekum) adalah posisi yang memiliki peran penting dalam struktur organisasi, terutama dalam hal pengelolaan administrasi, komunikasi, dan koordinasi internal. Sekum berfungsi sebagai penghubung utama antara pengurus organisasi dan anggota,
serta bertanggung jawab dalam memastikan semua kegiatan organisasi terlaksana dengan baik sesuai dengan tujuan dan kebijakan yang telah ditetapkan.'), 
(4, 'Wakil Sekretaris Umum', 'Wakil Sekretaris Umum (Wasekum) adalah posisi pendamping dari Sekretaris Umum dalam organisasi. Tugas utama Wakil Sekretaris Umum adalah membantu Sekretaris Umum dalam menjalankan tugas-tugas administrasi, koordinasi, dan komunikasi yang memastikan kelancaran operasional organisasi.
Selain itu, Wakil Sekretaris Umum sering kali juga diberi tanggung jawab untuk mengambil alih tugas Sekretaris Umum ketika yang bersangkutan tidak dapat hadir, atau membantu dalam kegiatan yang memerlukan koordinasi lebih intensif.'),
(5, 'Bendahara Umum', 'Bendahara Umum adalah posisi yang sangat penting dalam struktur organisasi yang bertanggung jawab atas pengelolaan keuangan organisasi. Tugas utama Bendahara Umum adalah memastikan bahwa keuangan organisasi dikelola dengan baik, transparan, dan sesuai dengan anggaran yang telah disepakati.
Bendahara Umum memainkan peran kunci dalam merencanakan, mencatat, dan melaporkan penggunaan dana organisasi, serta menjaga kestabilan keuangan agar organisasi dapat beroperasi dengan efektif.'), 
(6, 'Wakil Bendahara Umum', 'Wakil Bendahara Umum adalah posisi pendamping bagi Bendahara Umum dalam organisasi yang bertanggung jawab untuk membantu dalam pengelolaan keuangan organisasi. Wakil Bendahara Umum memiliki peran yang sangat penting dalam mendukung tugas-tugas administratif keuangan, 
mulai dari pencatatan transaksi hingga pengawasan penggunaan dana organisasi. Selain itu, Wakil Bendahara Umum juga dapat menggantikan Bendahara Umum dalam menjalankan tugasnya jika diperlukan.'),
(7, 'Koordinator Divisi', 'Koordinator Divisi adalah jabatan dalam struktur organisasi yang bertanggung jawab untuk memimpin, mengelola, dan mengkoordinasikan kegiatan dalam satu divisi atau bidang tertentu. Sebagai pemimpin dalam divisi tersebut, Koordinator Divisi berfungsi untuk memastikan bahwa semua tugas dan
kegiatan yang menjadi tanggung jawab divisi berjalan dengan baik dan sesuai dengan tujuan organisasi. Koordinator Divisi juga berperan sebagai penghubung antara divisi dengan pengurus lainnya, serta anggota yang terlibat dalam kegiatan divisi tersebut.'),
(8, 'Staf Divisi', 'Staf Divisi adalah anggota yang bekerja di bawah pimpinan Koordinator Divisi dan bertanggung jawab dalam melaksanakan tugas dan kegiatan operasional dalam suatu divisi. Meskipun mereka bukan pemimpin, staf divisi memiliki peran penting dalam mendukung keberhasilan program, proyek, 
atau aktivitas yang dijalankan oleh divisi tersebut. Staf divisi berperan dalam memastikan bahwa tugas-tugas yang diberikan selesai dengan baik dan sesuai dengan standar yang ditetapkan.');

