INSERT INTO dbo.Alamat(Kota, Kode_Pos, Kecamatan, Kabupaten, Provinsi)
VALUES('Bogor', '16111', 'Bogor Utara', 'Bogor', 'Jawa Barat'),
 ('Malang', '65115', 'Klojen', 'Malang', 'Jawa Timur'),
('Padang', '25112', 'Padang Barat', 'Padang', 'Sumatera Barat'),
 ('Samarinda', '75117', 'Sungai Kunjang', 'Samarinda', 'Kalimantan Timur'),
('Pontianak', '78113', 'Pontianak Selatan', 'Pontianak', 'Kalimantan Barat'),
 ('Tasikmalaya', '46112', 'Tawang', 'Tasikmalaya', 'Jawa Barat'),
('Pekanbaru', '28112', 'Sukajadi', 'Pekanbaru', 'Riau'),
('Banda Aceh', '23116', 'Banda Raya', 'Banda Aceh', 'Aceh'),
 ('Manado', '95111', 'Sario', 'Manado', 'Sulawesi Utara'),
 ('Kupang', '85111', 'Kelapa Lima', 'Kupang', 'Nusa Tenggara Timur'),
 ('Balikpapan', '76114', 'Balikpapan Barat', 'Balikpapan', 'Kalimantan Timur'),
 ('Banjarmasin', '70111', 'Banjarmasin Tengah', 'Banjarmasin', 'Kalimantan Selatan'),
 ('Ambon', '97124', 'Sirimau', 'Ambon', 'Maluku'),
 ('Gorontalo', '96128', 'Dumbo Raya', 'Gorontalo', 'Gorontalo'),
('Ternate', '97714', 'Ternate Tengah', 'Ternate', 'Maluku Utara'),
('Jayapura', '99111', 'Jayapura Selatan', 'Jayapura', 'Papua'),
('Mataram', '83115', 'Cakranegara', 'Mataram', 'Nusa Tenggara Barat'),
 ('Denpasar', '80113', 'Denpasar Timur', 'Denpasar', 'Bali'),
 ('Batam', '29432', 'Lubuk Baja', 'Batam', 'Kepulauan Riau'),
('Serang', '42111', 'Serang', 'Serang', 'Banten');

